version: '3.4'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - tests
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
  example:
    build:
      context: ../../
      dockerfile: example/advanced/Dockerfile
    command: ["./example/advanced/wait-and-run.sh", "mysql"]
    depends_on:
      - mysql
    networks:
      - tests

networks:
  tests:
    driver: bridge